### ISSUE TITLE
error while running runserver

### ISSUE THREAD

**Issue by chagara** [rocket-league-replays/rocket-league-replays#36]
hello,

was following the guide and was trying to runserver and got this error:

python manage.py runserver_plus 
Traceback (most recent call last):
  File "manage.py", line 24, in <module>
    except FileNotFoundError:
NameError: name 'FileNotFoundError' is not defined

**Comment by danielsamuels** [comment]
I think that means you're trying to run it on Python 2, this project requires Python 3.

**Comment by chagara** [comment]
I tried python3 manage.py runserver_plus and still get the same error.

**Comment by danielsamuels** [comment]
Are you sure your `python3` binary is _actually_ Python 3? If you run `python3` and go into the interactive session, what version does it print out?

**Comment by chagara** [comment]
this is what I get:
 @jcasanova  python3
Python 3.5.2 (default, Sep 10 2016, 08:21:44) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by chagara** [comment]
I started from scratch and this is what I get now:
Desktop  git_test  rocket-league-replays  1  python3 manage.py collectstatic -l --noinput
Traceback (most recent call last):
  File "manage.py", line 60, in <module>
    execute_from_command_line(sys.argv)
  File "/home/jcasanova/Desktop/git_test/rocket-league-replays/.venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/jcasanova/Desktop/git_test/rocket-league-replays/.venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/home/jcasanova/Desktop/git_test/rocket-league-replays/.venv/lib/python3.5/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/jcasanova/Desktop/git_test/rocket-league-replays/.venv/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/jcasanova/Desktop/git_test/rocket-league-replays/.venv/lib/python3.5/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/jcasanova/Desktop/git_test/rocket-league-replays/.venv/lib/python3.5/site-packages/djcelery/models.py", line 15, in <module>
    from celery.utils.timeutils import timedelta_seconds
ImportError: No module named 'celery.utils.timeutils'

**Comment by danielsamuels** [comment]
It might be a problem with the versions. Locally I have installed:

```
celery==3.1.23
django-celery==3.1.17
```

Could you give those a try? If that works I'll update the requirements file to specify the exact version.

**Comment by chagara** [comment]
now I get this error:

python3 manage.py runserver_plus
Traceback (most recent call last):
  File "manage.py", line 35, in <module>
    octane_release['name'],
KeyError: 'name'

**Comment by tfausak** [comment]
You probably need a GitHub API token: https://github.com/rocket-league-replays/rocket-league-replays/blob/f92eb6ad9dcc38420038aa1175317d369847cbc6/manage.py#L18

**Comment by chagara** [comment]
do I put that on the manage.py or is that something on the local.py ?

**Comment by tfausak** [comment]
It needs to go in an environment variable. Looks like you're using some type of Linux, so you can set it with `env GITHUB_TOKEN='blah' python3 manage.py ...`.

**Comment by danielsamuels** [comment]
I should probably make that system optional, I'm not used to other people using this code!

**Comment by chagara** [comment]
:) I'm really interested it in. I'll try to write down some notes on how it worked then send it to you.

**Comment by danielsamuels** [comment]
I don't think you're far off at this point, but any notes you have would be much appreciated!

**Comment by ScooterAmerica** [comment]
Im also having problems at  python3 manage.py collectstatic -l --noinput. Except Im getting an invalid syntax error in parser.py
Output: 
Secrets config not found, environment variables have not been set.
Traceback (most recent call last):
  File "manage.py", line 60, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/html/annamaics.com/public_html/rocketshare/.p3/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/var/www/html/annamaics.com/public_html/rocketshare/.p3/lib/python3.4/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/var/www/html/annamaics.com/public_html/rocketshare/.p3/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/var/www/html/annamaics.com/public_html/rocketshare/.p3/lib/python3.4/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/var/www/html/annamaics.com/public_html/rocketshare/.p3/lib/python3.4/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/var/www/html/annamaics.com/public_html/rocketshare/.p3/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/var/www/html/annamaics.com/public_html/rocketshare/rocket_league/apps/replays/models.py", line 16, in <module>
    from .parser import parse_replay_header, parse_replay_netstream
  File "/var/www/html/annamaics.com/public_html/rocketshare/rocket_league/apps/replays/parser.py", line 361
    actors[actor_id] = {**actors[actor_id], **value}
                         ^
SyntaxError: invalid syntax

**Comment by danielsamuels** [comment]
```{*actors[actor_id], *value}``` is Python 3.5+ syntax, you'll need to be using Python 3.5 or higher for it to run. What are you currently using?

**Comment by ScooterAmerica** [comment]
ahh that explains it. currently am on 3.4.
